<?php
// $Id: xoops_version.php,v 1.1 2006/03/27 08:42:21 mikhail Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <https://www.xoops.org>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
$modversion['name']        = "Shop";
$modversion['version']     = 0.2;
$modversion['author']      = 'Michael Baecker (webmaster@baecker.com)<br>Marko Predator Schmuck (webmaster@myxoopsshop.org)<br>http://www.myxoopsshop.org';
$modversion['description'] = "Shop System auf osCommerce MS2";
$modversion['credits']     = "The XOOPS Project<br>myXoopsForge";
$modversion['help']        = "news.html";
$modversion['license']     = "GPL see LICENSE";
$modversion['official']    = 1;
$modversion['image']       = "images/xoscadmin.png";
$modversion['dirname']     = "shop";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
$modversion['tables'][0]        = "shop_address_book";
$modversion['tables'][1]        = "shop_address_format";
$modversion['tables'][2]        = "shop_banners";
$modversion['tables'][3]        = "shop_banners_history";
$modversion['tables'][4]        = "shop_categories";
$modversion['tables'][5]        = "shop_categories_description";
$modversion['tables'][6]        = "shop_configuration";
$modversion['tables'][7]        = "shop_configuration_group";
$modversion['tables'][8]        = "shop_counter";
$modversion['tables'][9]        = "shop_counter_history";
$modversion['tables'][10]       = "shop_countries";
$modversion['tables'][11]       = "shop_currencies";
$modversion['tables'][12]       = "shop_customers";
$modversion['tables'][13]       = "shop_customers_basket";
$modversion['tables'][14]       = "shop_customers_basket_attributes";
$modversion['tables'][15]       = "shop_customers_info";
$modversion['tables'][16]       = "shop_languages";
$modversion['tables'][17]       = "shop_manufacturers";
$modversion['tables'][18]       = "shop_manufacturers_info";
$modversion['tables'][19]       = "shop_newsletters";
$modversion['tables'][20]       = "shop_orders";
$modversion['tables'][21]       = "shop_orders_products";
$modversion['tables'][22]       = "shop_orders_status";
$modversion['tables'][23]       = "shop_orders_status_history";
$modversion['tables'][24]       = "shop_orders_products_attributes";
$modversion['tables'][25]       = "shop_orders_products_download";
$modversion['tables'][26]       = "shop_orders_total";
$modversion['tables'][27]       = "shop_products";
$modversion['tables'][28]       = "shop_products_attributes";
$modversion['tables'][29]       = "shop_products_attributes_download";
$modversion['tables'][30]       = "shop_products_description";
$modversion['tables'][31]       = "shop_products_notifications";
$modversion['tables'][32]       = "shop_products_options";
$modversion['tables'][33]       = "shop_products_options_values";
$modversion['tables'][34]       = "shop_products_options_values_to_products_options";
$modversion['tables'][35]       = "shop_products_to_categories";
$modversion['tables'][36]       = "shop_reviews";
$modversion['tables'][37]       = "shop_reviews_description";
$modversion['tables'][38]       = "shop_sessions";
$modversion['tables'][39]       = "shop_specials";
$modversion['tables'][40]       = "shop_tax_class";
$modversion['tables'][41]       = "shop_tax_rates";
$modversion['tables'][42]       = "shop_geo_zones";
$modversion['tables'][43]       = "shop_whos_online";
$modversion['tables'][44]       = "shop_zones";
$modversion['tables'][45]       = "shop_zones_to_geo_zones";
$modversion['tables'][46]       = "shop_affiliate_affiliate";
$modversion['tables'][47]       = "shop_affiliate_banners";
$modversion['tables'][48]       = "shop_affiliate_banners_history";
$modversion['tables'][49]       = "shop_affiliate_clickthroughs";
$modversion['tables'][50]       = "shop_affiliate_news";
$modversion['tables'][51]       = "shop_affiliate_newsletter";
$modversion['tables'][52]       = "shop_affiliate_payment";
$modversion['tables'][53]       = "shop_affiliate_payment_status";
$modversion['tables'][54]       = "shop_affiliate_payment_status_history";
$modversion['tables'][55]       = "shop_affiliate_sales";

// Install things
// $modversion['onInstall'] = "includes/xoopsinstall.php";

// Admin things
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu']  = "admin/menu.php";

// Blocks
$modversion['blocks'][1]['file']         = "best_seller.php";
$modversion['blocks'][1]['name']         = "Shop Bestseller";
$modversion['blocks'][1]['description']  = "Shows most selled items";
$modversion['blocks'][1]['show_func']    = "b_shop_bestseller";
$modversion['blocks'][1]['template']     = 'shop_standard.html';
$modversion['blocks'][2]['file']         = "categories.php";
$modversion['blocks'][2]['name']         = "Shop Categories";
$modversion['blocks'][2]['description']  = "Shows Shop categories";
$modversion['blocks'][2]['show_func']    = "b_shop_categories";
$modversion['blocks'][2]['template']     = 'shop_standard.html';
$modversion['blocks'][3]['file']         = "currencies.php";
$modversion['blocks'][3]['name']         = "Shop Currencies";
$modversion['blocks'][3]['description']  = "Shows Shop Currencies";
$modversion['blocks'][3]['show_func']    = "b_shop_currencies";
$modversion['blocks'][3]['template']     = 'shop_standard.html';
$modversion['blocks'][4]['file']         = "information.php";
$modversion['blocks'][4]['name']         = "Shop Information";
$modversion['blocks'][4]['description']  = "Shows Shop Information";
$modversion['blocks'][4]['show_func']    = "b_shop_information";
$modversion['blocks'][4]['template']     = 'shop_standard.html';
$modversion['blocks'][5]['file']         = "shopping_cart.php";
$modversion['blocks'][5]['name']         = "Shop Cart";
$modversion['blocks'][5]['description']  = "Shows Shopping Cart";
$modversion['blocks'][5]['show_func']    = "b_shop_cart";
$modversion['blocks'][5]['template']     = 'shop_standard.html';
$modversion['blocks'][6]['file']         = "specials.php";
$modversion['blocks'][6]['name']         = "Shop Specials";
$modversion['blocks'][6]['description']  = "Shows Shop Specials";
$modversion['blocks'][6]['show_func']    = "b_shop_specials";
$modversion['blocks'][6]['template']     = 'shop_standard.html';
$modversion['blocks'][7]['file']         = "whats_new.php";
$modversion['blocks'][7]['name']         = "Shop New Products";
$modversion['blocks'][7]['description']  = "Shows Shop New Products";
$modversion['blocks'][7]['show_func']    = "b_shop_whatsnew";
$modversion['blocks'][7]['template']     = 'shop_standard.html';
$modversion['blocks'][8]['file']         = "manufacturers.php";
$modversion['blocks'][8]['name']         = "Shop Manufacturers";
$modversion['blocks'][8]['description']  = "Shows Shop Manufactures";
$modversion['blocks'][8]['show_func']    = "b_shop_manufacturers";
$modversion['blocks'][8]['template']     = 'shop_standard.html';
$modversion['blocks'][9]['file']         = "search.php";
$modversion['blocks'][9]['name']         = "Shop Search";
$modversion['blocks'][9]['description']  = "Shows Shop Search";
$modversion['blocks'][9]['show_func']    = "b_shop_search";
$modversion['blocks'][9]['template']     = 'shop_standard.html';
$modversion['blocks'][10]['file']        = "tell_a_friend.php";
$modversion['blocks'][10]['name']        = "Shop Tell a Friend";
$modversion['blocks'][10]['description'] = "Shows Shop Tell a Friend";
$modversion['blocks'][10]['show_func']   = "b_shop_tellafriend";
$modversion['blocks'][10]['template']    = 'shop_standard.html';
$modversion['blocks'][11]['file']        = "displaycategories.php";
$modversion['blocks'][11]['name']        = "Display Categories";
$modversion['blocks'][11]['description'] = "Display Categories";
$modversion['blocks'][11]['show_func']   = "b_shop_displaycategories";
$modversion['blocks'][11]['templates']   = 'shop_standard.html';
$modversion['blocks'][12]['file']        = "reviews.php";
$modversion['blocks'][12]['name']        = "Reviews";
$modversion['blocks'][12]['description'] = "Reviews";
$modversion['blocks'][12]['show_func']   = "b_shop_reviews";
$modversion['blocks'][12]['templates']   = 'shop_standard.html';
$modversion['blocks'][13]['file']        = "affiliate.php";
$modversion['blocks'][13]['name']        = "affiliate";
$modversion['blocks'][13]['description'] = "Affiliate";
$modversion['blocks'][13]['show_func']   = "b_shop_affiliate";
$modversion['blocks'][13]['templates']   = 'shop_standard.html';

// Menu
$modversion['hasMain']        = 1;
$modversion['sub'][1]['name'] = "Entrance";
$modversion['sub'][1]['url']  = "index.php";
$modversion['sub'][2]['name'] = "Specials";
$modversion['sub'][2]['url']  = "specials.php";
$modversion['sub'][3]['name'] = "Shopping Cart";
$modversion['sub'][3]['url']  = "shopping_cart.php";
$modversion['sub'][4]['name'] = "Checkout";
$modversion['sub'][4]['url']  = "checkout_shipping.php";
$modversion['sub'][5]['name'] = "Account";
$modversion['sub'][5]['url']  = "account.php";
$modversion['sub'][6]['name'] = "Affiliate";
$modversion['sub'][6]['url']  = "affiliate_affiliate.php";

// Search
$modversion['hasSearch'] = 0;

// Comments
$modversion['hasComments'] = 0;
